Route110_TrickHouseEntrance_MapScripts:: @ 8269A50
	
	.byte 0




Route110_TrickHouseEnd_Movement_269E36: @ 8269E36
Route110_TrickHouseEntrance_Movement_269E36: @ 8269E36
	face_up
	delay_4
	face_left
	delay_4
	face_down
	delay_4
	face_right
	delay_4
	step_end

Route110_TrickHouseEnd_Movement_269E3F: @ 8269E3F
Route110_TrickHouseEntrance_Movement_269E3F: @ 8269E3F
	face_up
	disable_anim
	slide_up
	slide_up
	slide_up
	slide_up
	slide_up
	slide_up
	step_end

Route110_TrickHouseEntrance_EventScript_26A0D3:: @ 826A0D3
Route110_TrickHouseEntrance_EventScript_26A3F8:: @ 826A3F8
Route110_TrickHouseEntrance_EventScript_269D3B:: @ 8269D3B
Route110_TrickHouseEntrance_EventScript_26A22A:: @ 826A22A
	end


Route110_TrickHousePuzzle1_EventScript_26A3DB:: @ 826A3DB
Route110_TrickHousePuzzle2_EventScript_26A3DB:: @ 826A3DB
Route110_TrickHousePuzzle3_EventScript_26A3DB:: @ 826A3DB
Route110_TrickHousePuzzle4_EventScript_26A3DB:: @ 826A3DB
Route110_TrickHousePuzzle5_EventScript_26A3DB:: @ 826A3DB
Route110_TrickHousePuzzle6_EventScript_26A3DB:: @ 826A3DB
Route110_TrickHousePuzzle7_EventScript_26A3DB:: @ 826A3DB
Route110_TrickHousePuzzle8_EventScript_26A3DB:: @ 826A3DB
	end

Route110_TrickHousePuzzle1_EventScript_26A3E5:: @ 826A3E5
Route110_TrickHousePuzzle2_EventScript_26A3E5:: @ 826A3E5
Route110_TrickHousePuzzle3_EventScript_26A3E5:: @ 826A3E5
Route110_TrickHousePuzzle4_EventScript_26A3E5:: @ 826A3E5
Route110_TrickHousePuzzle5_EventScript_26A3E5:: @ 826A3E5
Route110_TrickHousePuzzle6_EventScript_26A3E5:: @ 826A3E5
Route110_TrickHousePuzzle7_EventScript_26A3E5:: @ 826A3E5
Route110_TrickHousePuzzle8_EventScript_26A3E5:: @ 826A3E5
	end
