#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

// Map Group 0
#define MAP_TRICK_HOUSE_DEV_ENTRANCE (0 | (0 << 8))
#define MAP_TRICK_HOUSE_EXT          (1 | (0 << 8))
#define MAP_TRICK_HOUSE_ENTRANCE     (2 | (0 << 8))
#define MAP_TRICK_HOUSE_END          (3 | (0 << 8))
#define MAP_TRICK_HOUSE_CORRIDOR     (4 | (0 << 8))
#define MAP_TRICK_HOUSE_TREE_HOUSE   (5 | (0 << 8))
#define MAP_TRICK_HOUSE_RESTROOM     (6 | (0 << 8))

// Map Group 1
#define MAP_TEST_MAP_HALLWAY       (0 | (1 << 8))
#define MAP_TEST_LAYOUT_SWITCHING  (1 | (1 << 8))
#define MAP_TEST_LAYOUT_SWITCHING2 (2 | (1 << 8))
#define MAP_TEST_MIRROR_MOVEMENT   (3 | (1 << 8))
#define MAP_TEST_COPY_MOVEMENT     (4 | (1 << 8))
#define MAP_INDOOR_MAP             (5 | (1 << 8))
#define MAP_TEST_MUSIC_ROOM        (6 | (1 << 8))
#define MAP_TEST_ACRO_BIKE_MAP     (7 | (1 << 8))

// Map Group 2
#define MAP_MAUVILLE_CITY_CUTSCENE (0 | (2 << 8))
#define MAP_RUSTBORO_CITY_CUTSCENE (1 | (2 << 8))

// Map Group 3
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (3 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (3 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (3 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (3 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (3 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (3 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (3 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (3 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (3 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (3 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (3 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (3 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (3 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (3 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (3 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (3 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (3 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (3 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (3 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (3 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (3 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (3 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (3 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (3 << 8))

// Map Group 4
#define MAP_EMPTY_PUZZLE           (0 | (4 << 8))
#define MAP_LEDGE_MOUNTAIN_SUPPORT (1 | (4 << 8))
#define MAP_WATER_TEMPLE_LV1       (2 | (4 << 8))
#define MAP_WATER_TEMPLE_LV2       (3 | (4 << 8))
#define MAP_TRAINER_HILL_TEMPLATE  (4 | (4 << 8))
#define MAP_FAKE_SECRET_BASE_CAVE  (5 | (4 << 8))
#define MAP_SUSPENDED_MAZE_B1      (6 | (4 << 8))
#define MAP_WATER_TEMPLE_SECRET    (7 | (4 << 8))
#define MAP_DIVE_MAZE_UNDERWATER   (8 | (4 << 8))

// Map Group 5
#define MAP_PETALBURG_CITY   (0 | (5 << 8))
#define MAP_SLATEPORT_CITY   (1 | (5 << 8))
#define MAP_MAUVILLE_CITY    (2 | (5 << 8))
#define MAP_RUSTBORO_CITY    (3 | (5 << 8))
#define MAP_FORTREE_CITY     (4 | (5 << 8))
#define MAP_LILYCOVE_CITY    (5 | (5 << 8))
#define MAP_SOOTOPOLIS_CITY  (6 | (5 << 8))
#define MAP_EVER_GRANDE_CITY (7 | (5 << 8))
#define MAP_LITTLEROOT_TOWN  (8 | (5 << 8))
#define MAP_OLDALE_TOWN      (9 | (5 << 8))
#define MAP_DEWFORD_TOWN     (10 | (5 << 8))
#define MAP_LAVARIDGE_TOWN   (11 | (5 << 8))
#define MAP_FALLARBOR_TOWN   (12 | (5 << 8))
#define MAP_VERDANTURF_TOWN  (13 | (5 << 8))
#define MAP_PACIFIDLOG_TOWN  (14 | (5 << 8))
#define MAP_ROUTE101         (15 | (5 << 8))
#define MAP_ROUTE102         (16 | (5 << 8))
#define MAP_ROUTE103         (17 | (5 << 8))
#define MAP_ROUTE104         (18 | (5 << 8))
#define MAP_ROUTE105         (19 | (5 << 8))
#define MAP_ROUTE106         (20 | (5 << 8))
#define MAP_ROUTE107         (21 | (5 << 8))
#define MAP_ROUTE108         (22 | (5 << 8))
#define MAP_ROUTE109         (23 | (5 << 8))
#define MAP_ROUTE111         (24 | (5 << 8))
#define MAP_ROUTE112         (25 | (5 << 8))
#define MAP_ROUTE113         (26 | (5 << 8))
#define MAP_ROUTE114         (27 | (5 << 8))
#define MAP_ROUTE115         (28 | (5 << 8))
#define MAP_ROUTE116         (29 | (5 << 8))
#define MAP_ROUTE117         (30 | (5 << 8))
#define MAP_ROUTE118         (31 | (5 << 8))
#define MAP_ROUTE119         (32 | (5 << 8))
#define MAP_ROUTE120         (33 | (5 << 8))
#define MAP_ROUTE121         (34 | (5 << 8))
#define MAP_ROUTE122         (35 | (5 << 8))
#define MAP_ROUTE123         (36 | (5 << 8))
#define MAP_ROUTE124         (37 | (5 << 8))
#define MAP_ROUTE125         (38 | (5 << 8))
#define MAP_ROUTE126         (39 | (5 << 8))
#define MAP_ROUTE127         (40 | (5 << 8))
#define MAP_ROUTE128         (41 | (5 << 8))
#define MAP_ROUTE129         (42 | (5 << 8))
#define MAP_ROUTE130         (43 | (5 << 8))
#define MAP_ROUTE131         (44 | (5 << 8))
#define MAP_ROUTE132         (45 | (5 << 8))
#define MAP_ROUTE133         (46 | (5 << 8))
#define MAP_ROUTE134         (47 | (5 << 8))

// Map Group 6
#define MAP_PUZZLE_TRICK_HOUSE_TRAPDOORS    (0 | (6 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_SPINTILES    (1 | (6 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_ORIGINAL1    (2 | (6 << 8))
#define MAP_PUZZLE_ILEX_FOREST              (3 | (6 << 8))
#define MAP_PUZZLE_SOOT_SACK_MAZE           (4 | (6 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_SLIP_SLIDING (5 | (6 << 8))
#define MAP_PUZZLE_FALLING_WATER            (6 | (6 << 8))
#define MAP_PUZZLE_TRAINER_HILL1            (7 | (6 << 8))
#define MAP_PUZZLE_TRAINER_HILL2            (8 | (6 << 8))
#define MAP_PUZZLE_TRAINER_HILL3            (9 | (6 << 8))
#define MAP_PUZZLE_TRAINER_HILL4            (10 | (6 << 8))
#define MAP_PUZZLE_SUSPENDED_MAZE           (11 | (6 << 8))
#define MAP_PUZZLE_ICE_PATH                 (12 | (6 << 8))
#define MAP_PUZZLE_TIC_RAC_TOE              (13 | (6 << 8))
#define MAP_PUZZLE_STEALTH_MISSION          (14 | (6 << 8))
#define MAP_PUZZLE_MURDER_EXPRESS           (15 | (6 << 8))
#define MAP_PUZZLE_ELITE_FLOOR              (16 | (6 << 8))
#define MAP_PUZZLE_DIVE_MAZE                (17 | (6 << 8))
#define MAP_PUZZLE_IMPOSTER_REFLECTION      (18 | (6 << 8))

// Map Group 7
#define MAP_PUZZLE_LOST_WOODS1_ENTRANCE (0 | (7 << 8))
#define MAP_PUZZLE_LOST_WOODS2_ENTRANCE (1 | (7 << 8))
#define MAP_PUZZLE_LOST_WOODS3_ENTRANCE (2 | (7 << 8))
#define MAP_PUZZLE_LOST_WOODS4_ENTRANCE (3 | (7 << 8))
#define MAP_LOST_WOODS1_EXIT            (4 | (7 << 8))
#define MAP_LOST_WOODS2_EXIT            (5 | (7 << 8))
#define MAP_LOST_WOODS3_EXIT            (6 | (7 << 8))
#define MAP_LOST_WOODS4_EXIT            (7 | (7 << 8))
#define MAP_LOST_WOODS1_ROOM0           (8 | (7 << 8))
#define MAP_LOST_WOODS1_ROOM1           (9 | (7 << 8))
#define MAP_LOST_WOODS1_ROOM2           (10 | (7 << 8))
#define MAP_LOST_WOODS1_ROOM3           (11 | (7 << 8))
#define MAP_LOST_WOODS1_ROOM4           (12 | (7 << 8))
#define MAP_LOST_WOODS1_ROOM5           (13 | (7 << 8))
#define MAP_LOST_WOODS1_ROOM6           (14 | (7 << 8))
#define MAP_LOST_WOODS1_ROOM7           (15 | (7 << 8))
#define MAP_LOST_WOODS1_ROOM8           (16 | (7 << 8))
#define MAP_LOST_WOODS1_ROOM9           (17 | (7 << 8))
#define MAP_LOST_WOODS1_ROOM10          (18 | (7 << 8))
#define MAP_LOST_WOODS1_UNDERWATER      (19 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM0           (20 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_A1         (21 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_A2         (22 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_A3         (23 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_A4         (24 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_A5         (25 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_A6         (26 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_B1         (27 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_B2         (28 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_B3         (29 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_B4         (30 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_B5         (31 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_B6         (32 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_B7         (33 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_B8         (34 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_B9         (35 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_C1         (36 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_C2         (37 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_C3         (38 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_C4         (39 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_C5         (40 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_C6         (41 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_D1         (42 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_D2         (43 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_D3         (44 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_D4         (45 | (7 << 8))
#define MAP_LOST_WOODS4_ROOM_D5         (46 | (7 << 8))

// Map Group 8
#define MAP_PUZZLE_DESERT_OASIS (0 | (8 << 8))
#define MAP_DESERT_EAST         (1 | (8 << 8))
#define MAP_DESERT_NORTH        (2 | (8 << 8))
#define MAP_DESERT_WEST         (3 | (8 << 8))
#define MAP_DESERT_SOUTH        (4 | (8 << 8))

// Map Group 9
#define MAP_TRICK_TREAT_PETALBURG_CITY  (0 | (9 << 8))
#define MAP_TRICK_TREAT_MOSSDEEP_CITY   (1 | (9 << 8))
#define MAP_TRICK_TREAT_FORTREE_CITY    (2 | (9 << 8))
#define MAP_TRICK_TREAT_SLATEPORT_CITY1 (3 | (9 << 8))
#define MAP_TRICK_TREAT_SLATEPORT_CITY2 (4 | (9 << 8))
#define MAP_TRICK_TREAT_ALTO_MARE1      (5 | (9 << 8))
#define MAP_TRICK_TREAT_ALTO_MARE2      (6 | (9 << 8))
#define MAP_TRICK_TREAT_GOLDENROD_CITY  (7 | (9 << 8))

// Map Group 10
#define MAP_PUZZLE_SPOT_DIFFERENCE_HALLWAY (0 | (10 << 8))
#define MAP_PUZZLE_SPOT_DIFFERENCE_1_LEFT  (1 | (10 << 8))
#define MAP_PUZZLE_SPOT_DIFFERENCE_1_RIGHT (2 | (10 << 8))
#define MAP_PUZZLE_SPOT_DIFFERENCE_2_LEFT  (3 | (10 << 8))
#define MAP_PUZZLE_SPOT_DIFFERENCE_2_RIGHT (4 | (10 << 8))
#define MAP_PUZZLE_SPOT_DIFFERENCE_3_LEFT  (5 | (10 << 8))
#define MAP_PUZZLE_SPOT_DIFFERENCE_3_RIGHT (6 | (10 << 8))

// Map Group 11
#define MAP_PUZZLE_META_PUZZLE_CAVE (0 | (11 << 8))

// Map Group 12
#define MAP_PUZZLE_TRICK_HOUSE_CUT       (0 | (12 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_ORIGINAL2 (1 | (12 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_ORIGINAL3 (2 | (12 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_ORIGINAL4 (3 | (12 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_ORIGINAL5 (4 | (12 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_ORIGINAL6 (5 | (12 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_ORIGINAL7 (6 | (12 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_ORIGINAL8 (7 | (12 << 8))
#define MAP_PUZZLE_TIN_TOWER_CLIMB       (8 | (12 << 8))
#define MAP_PUZZLE_WATER_TEMPLE          (9 | (12 << 8))
#define MAP_PUZZLE_MUSIC_NOTE_TILES      (10 | (12 << 8))
#define MAP_PUZZLE_LEDGE_MOUNTAIN        (11 | (12 << 8))
#define MAP_PUZZLE_WILKE                 (12 | (12 << 8))
#define MAP_PUZZLE_ROUTE110              (13 | (12 << 8))
#define MAP_PUZZLE_LOSS_FLOOR1           (14 | (12 << 8))
#define MAP_PUZZLE_LOSS_FLOOR2           (15 | (12 << 8))
#define MAP_PUZZLE_TWIN_MEMORIES         (16 | (12 << 8))
#define MAP_PUZZLE_HIDDEN_MAZE           (17 | (12 << 8))

#define MAP_GROUPS_COUNT 13

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
