#ifndef GUARD_CONSTANTS_MAP_SCRIPTS_H
#define GUARD_CONSTANTS_MAP_SCRIPTS_H

#define MAP_SCRIPT_ON_LOAD                      1
#define MAP_SCRIPT_ON_FRAME_TABLE               2
#define MAP_SCRIPT_ON_TRANSITION                3
#define MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE       4
#define MAP_SCRIPT_ON_RESUME                    5
#define MAP_SCRIPT_ON_DIVE_WARP                 6
#define MAP_SCRIPT_ON_RETURN_TO_FIELD           7
#define MAP_SCRIPT_ON_SPAWN_EVENT_OBJECT        8

#define MAP_SCRIPT_PUZZLE_HEADER_NAME          20
#define MAP_SCRIPT_PUZZLE_HEADER_AUTHOR        21
#define MAP_SCRIPT_PUZZLE_HEADER_PREREQ_LIST   22
#define MAP_SCRIPT_PUZZLE_HEADER_POST_LIST     23
#define MAP_SCRIPT_PUZZLE_HEADER_ADJECTIVE     24
#define MAP_SCRIPT_PUZZLE_HEADER_QUIP          25
#define MAP_SCRIPT_PUZZLE_META_VARIABLES       26
#define MAP_SCRIPT_PUZZLE_SETUP_SCRIPT         27
#define MAP_SCRIPT_PUZZLE_TEARDOWN_SCRIPT      28
#define MAP_SCRIPT_PUZZLE_CUSTOM_INTRO         29
#define MAP_SCRIPT_PUZZLE_CANDY_LIST           30
#define MAP_SCRIPT_PUZZLE_DEV_COMMENTARY       31
#define MAP_SCRIPT_PUZZLE_EXIT_SCRIPT          32
#define MAP_SCRIPT_PUZZLE_BLACKOUT_SCRIPT      33
#define MAP_SCRIPT_PUZZLE_ESCAPE_SCRIPT        34
#define MAP_SCRIPT_PUZZLE_FRIEND_COMMENTARY    35

#endif // GUARD_CONSTANTS_MAP_SCRIPTS_H
