#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

// Map Group 0
#define MAP_TRICK_HOUSE_DEV_ENTRANCE (0 | (0 << 8))
#define MAP_TRICK_HOUSE_EXT          (1 | (0 << 8))
#define MAP_TRICK_HOUSE_ENTRANCE     (2 | (0 << 8))
#define MAP_TRICK_HOUSE_END          (3 | (0 << 8))
#define MAP_TRICK_HOUSE_CORRIDOR     (4 | (0 << 8))

// Map Group 1
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1 (0 | (1 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2 (1 | (1 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3 (2 | (1 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4 (3 | (1 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6 (4 | (1 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7 (5 | (1 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8 (6 | (1 << 8))
#define MAP_TEST_MAP_HALLWAY             (7 | (1 << 8))
#define MAP_TEST_LAYOUT_SWITCHING        (8 | (1 << 8))
#define MAP_TEST_LAYOUT_SWITCHING2       (9 | (1 << 8))
#define MAP_EMPTY_PUZZLE                 (10 | (1 << 8))
#define MAP_WATER_TEMPLE_LV1             (11 | (1 << 8))
#define MAP_WATER_TEMPLE_LV2             (12 | (1 << 8))
#define MAP_TEST_MIRROR_MOVEMENT         (13 | (1 << 8))
#define MAP_TEST_COPY_MOVEMENT           (14 | (1 << 8))

// Map Group 2
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (2 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (2 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (2 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (2 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (2 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (2 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (2 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (2 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (2 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (2 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (2 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (2 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (2 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (2 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (2 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (2 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (2 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (2 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (2 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (2 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (2 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (2 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (2 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (2 << 8))

// Map Group 3
#define MAP_PETALBURG_CITY         (0 | (3 << 8))
#define MAP_SLATEPORT_CITY         (1 | (3 << 8))
#define MAP_MAUVILLE_CITY          (2 | (3 << 8))
#define MAP_RUSTBORO_CITY          (3 | (3 << 8))
#define MAP_FORTREE_CITY           (4 | (3 << 8))
#define MAP_LILYCOVE_CITY          (5 | (3 << 8))
#define MAP_MOSSDEEP_CITY          (6 | (3 << 8))
#define MAP_SOOTOPOLIS_CITY        (7 | (3 << 8))
#define MAP_EVER_GRANDE_CITY       (8 | (3 << 8))
#define MAP_LITTLEROOT_TOWN        (9 | (3 << 8))
#define MAP_OLDALE_TOWN            (10 | (3 << 8))
#define MAP_DEWFORD_TOWN           (11 | (3 << 8))
#define MAP_LAVARIDGE_TOWN         (12 | (3 << 8))
#define MAP_FALLARBOR_TOWN         (13 | (3 << 8))
#define MAP_VERDANTURF_TOWN        (14 | (3 << 8))
#define MAP_PACIFIDLOG_TOWN        (15 | (3 << 8))
#define MAP_ROUTE101               (16 | (3 << 8))
#define MAP_ROUTE102               (17 | (3 << 8))
#define MAP_ROUTE103               (18 | (3 << 8))
#define MAP_ROUTE104               (19 | (3 << 8))
#define MAP_ROUTE105               (20 | (3 << 8))
#define MAP_ROUTE106               (21 | (3 << 8))
#define MAP_ROUTE107               (22 | (3 << 8))
#define MAP_ROUTE108               (23 | (3 << 8))
#define MAP_ROUTE109               (24 | (3 << 8))
#define MAP_ROUTE110               (25 | (3 << 8))
#define MAP_ROUTE111               (26 | (3 << 8))
#define MAP_ROUTE112               (27 | (3 << 8))
#define MAP_ROUTE113               (28 | (3 << 8))
#define MAP_ROUTE114               (29 | (3 << 8))
#define MAP_ROUTE115               (30 | (3 << 8))
#define MAP_ROUTE116               (31 | (3 << 8))
#define MAP_ROUTE117               (32 | (3 << 8))
#define MAP_ROUTE118               (33 | (3 << 8))
#define MAP_ROUTE119               (34 | (3 << 8))
#define MAP_ROUTE120               (35 | (3 << 8))
#define MAP_ROUTE121               (36 | (3 << 8))
#define MAP_ROUTE122               (37 | (3 << 8))
#define MAP_ROUTE123               (38 | (3 << 8))
#define MAP_ROUTE124               (39 | (3 << 8))
#define MAP_ROUTE125               (40 | (3 << 8))
#define MAP_ROUTE126               (41 | (3 << 8))
#define MAP_ROUTE127               (42 | (3 << 8))
#define MAP_ROUTE128               (43 | (3 << 8))
#define MAP_ROUTE129               (44 | (3 << 8))
#define MAP_ROUTE130               (45 | (3 << 8))
#define MAP_ROUTE131               (46 | (3 << 8))
#define MAP_ROUTE132               (47 | (3 << 8))
#define MAP_ROUTE133               (48 | (3 << 8))
#define MAP_ROUTE134               (49 | (3 << 8))
#define MAP_LEDGE_MOUNTAIN_SUPPORT (50 | (3 << 8))

// Map Group 4
#define MAP_PUZZLE_TRICK_HOUSE_CUT       (0 | (4 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_TRAPDOORS (1 | (4 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_SPINTILES (2 | (4 << 8))
#define MAP_PUZZLE_TIN_TOWER_CLIMB       (3 | (4 << 8))
#define MAP_PUZZLE_WATER_TEMPLE          (4 | (4 << 8))
#define MAP_PUZZLE_MUSIC_NOTE_TILES      (5 | (4 << 8))
#define MAP_PUZZLE_LEDGE_MOUNTAIN        (6 | (4 << 8))
#define MAP_PUZZLE_WILKE                 (7 | (4 << 8))

// Map Group 5
#define MAP_PUZZLE_LOST_WOODS1_ENTRANCE (0 | (5 << 8))
#define MAP_PUZZLE_LOST_WOODS2_ENTRANCE (1 | (5 << 8))
#define MAP_PUZZLE_LOST_WOODS3_ENTRANCE (2 | (5 << 8))
#define MAP_PUZZLE_LOST_WOODS4_ENTRANCE (3 | (5 << 8))
#define MAP_LOST_WOODS1_EXIT            (4 | (5 << 8))
#define MAP_LOST_WOODS2_EXIT            (5 | (5 << 8))
#define MAP_LOST_WOODS3_EXIT            (6 | (5 << 8))
#define MAP_LOST_WOODS4_EXIT            (7 | (5 << 8))
#define MAP_LOST_WOODS1_ROOM0           (8 | (5 << 8))
#define MAP_LOST_WOODS1_ROOM1           (9 | (5 << 8))
#define MAP_LOST_WOODS1_ROOM2           (10 | (5 << 8))
#define MAP_LOST_WOODS1_ROOM3           (11 | (5 << 8))
#define MAP_LOST_WOODS1_ROOM4           (12 | (5 << 8))
#define MAP_LOST_WOODS1_ROOM5           (13 | (5 << 8))
#define MAP_LOST_WOODS1_ROOM6           (14 | (5 << 8))
#define MAP_LOST_WOODS1_ROOM7           (15 | (5 << 8))
#define MAP_LOST_WOODS1_ROOM8           (16 | (5 << 8))
#define MAP_LOST_WOODS1_ROOM9           (17 | (5 << 8))
#define MAP_LOST_WOODS1_ROOM10          (18 | (5 << 8))

#define MAP_GROUPS_COUNT 6

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
