#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

// Map Group 0
#define MAP_TRICK_HOUSE_DEV_ENTRANCE (0 | (0 << 8))
#define MAP_TRICK_HOUSE_EXT          (1 | (0 << 8))
#define MAP_TRICK_HOUSE_ENTRANCE     (2 | (0 << 8))
#define MAP_TRICK_HOUSE_END          (3 | (0 << 8))
#define MAP_TRICK_HOUSE_CORRIDOR     (4 | (0 << 8))

// Map Group 1
#define MAP_TEST_MAP_HALLWAY       (0 | (1 << 8))
#define MAP_TEST_LAYOUT_SWITCHING  (1 | (1 << 8))
#define MAP_TEST_LAYOUT_SWITCHING2 (2 | (1 << 8))
#define MAP_TEST_MIRROR_MOVEMENT   (3 | (1 << 8))
#define MAP_TEST_COPY_MOVEMENT     (4 | (1 << 8))
#define MAP_INDOOR_MAP             (5 | (1 << 8))

// Map Group 2
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (2 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (2 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (2 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (2 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (2 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (2 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (2 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (2 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (2 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (2 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (2 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (2 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (2 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (2 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (2 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (2 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (2 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (2 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (2 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (2 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (2 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (2 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (2 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (2 << 8))

// Map Group 3
#define MAP_EMPTY_PUZZLE           (0 | (3 << 8))
#define MAP_LEDGE_MOUNTAIN_SUPPORT (1 | (3 << 8))
#define MAP_WATER_TEMPLE_LV1       (2 | (3 << 8))
#define MAP_WATER_TEMPLE_LV2       (3 | (3 << 8))
#define MAP_FAKE_SECRET_BASE_CAVE  (4 | (3 << 8))

// Map Group 4
#define MAP_PETALBURG_CITY   (0 | (4 << 8))
#define MAP_SLATEPORT_CITY   (1 | (4 << 8))
#define MAP_MAUVILLE_CITY    (2 | (4 << 8))
#define MAP_RUSTBORO_CITY    (3 | (4 << 8))
#define MAP_FORTREE_CITY     (4 | (4 << 8))
#define MAP_LILYCOVE_CITY    (5 | (4 << 8))
#define MAP_SOOTOPOLIS_CITY  (6 | (4 << 8))
#define MAP_EVER_GRANDE_CITY (7 | (4 << 8))
#define MAP_LITTLEROOT_TOWN  (8 | (4 << 8))
#define MAP_OLDALE_TOWN      (9 | (4 << 8))
#define MAP_DEWFORD_TOWN     (10 | (4 << 8))
#define MAP_LAVARIDGE_TOWN   (11 | (4 << 8))
#define MAP_FALLARBOR_TOWN   (12 | (4 << 8))
#define MAP_VERDANTURF_TOWN  (13 | (4 << 8))
#define MAP_PACIFIDLOG_TOWN  (14 | (4 << 8))
#define MAP_ROUTE101         (15 | (4 << 8))
#define MAP_ROUTE102         (16 | (4 << 8))
#define MAP_ROUTE103         (17 | (4 << 8))
#define MAP_ROUTE104         (18 | (4 << 8))
#define MAP_ROUTE105         (19 | (4 << 8))
#define MAP_ROUTE106         (20 | (4 << 8))
#define MAP_ROUTE107         (21 | (4 << 8))
#define MAP_ROUTE108         (22 | (4 << 8))
#define MAP_ROUTE109         (23 | (4 << 8))
#define MAP_ROUTE111         (24 | (4 << 8))
#define MAP_ROUTE112         (25 | (4 << 8))
#define MAP_ROUTE113         (26 | (4 << 8))
#define MAP_ROUTE114         (27 | (4 << 8))
#define MAP_ROUTE115         (28 | (4 << 8))
#define MAP_ROUTE116         (29 | (4 << 8))
#define MAP_ROUTE117         (30 | (4 << 8))
#define MAP_ROUTE118         (31 | (4 << 8))
#define MAP_ROUTE119         (32 | (4 << 8))
#define MAP_ROUTE120         (33 | (4 << 8))
#define MAP_ROUTE121         (34 | (4 << 8))
#define MAP_ROUTE122         (35 | (4 << 8))
#define MAP_ROUTE123         (36 | (4 << 8))
#define MAP_ROUTE124         (37 | (4 << 8))
#define MAP_ROUTE125         (38 | (4 << 8))
#define MAP_ROUTE126         (39 | (4 << 8))
#define MAP_ROUTE127         (40 | (4 << 8))
#define MAP_ROUTE128         (41 | (4 << 8))
#define MAP_ROUTE129         (42 | (4 << 8))
#define MAP_ROUTE130         (43 | (4 << 8))
#define MAP_ROUTE131         (44 | (4 << 8))
#define MAP_ROUTE132         (45 | (4 << 8))
#define MAP_ROUTE133         (46 | (4 << 8))
#define MAP_ROUTE134         (47 | (4 << 8))

// Map Group 5
#define MAP_PUZZLE_TRICK_HOUSE_TRAPDOORS    (0 | (5 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_SPINTILES    (1 | (5 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_ORIGINAL1    (2 | (5 << 8))
#define MAP_PUZZLE_ILEX_FOREST              (3 | (5 << 8))
#define MAP_PUZZLE_SOOT_SACK_MAZE           (4 | (5 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_SLIP_SLIDING (5 | (5 << 8))

// Map Group 6
#define MAP_PUZZLE_LOST_WOODS1_ENTRANCE (0 | (6 << 8))
#define MAP_PUZZLE_LOST_WOODS2_ENTRANCE (1 | (6 << 8))
#define MAP_PUZZLE_LOST_WOODS3_ENTRANCE (2 | (6 << 8))
#define MAP_PUZZLE_LOST_WOODS4_ENTRANCE (3 | (6 << 8))
#define MAP_LOST_WOODS1_EXIT            (4 | (6 << 8))
#define MAP_LOST_WOODS2_EXIT            (5 | (6 << 8))
#define MAP_LOST_WOODS3_EXIT            (6 | (6 << 8))
#define MAP_LOST_WOODS4_EXIT            (7 | (6 << 8))
#define MAP_LOST_WOODS1_ROOM0           (8 | (6 << 8))
#define MAP_LOST_WOODS1_ROOM1           (9 | (6 << 8))
#define MAP_LOST_WOODS1_ROOM2           (10 | (6 << 8))
#define MAP_LOST_WOODS1_ROOM3           (11 | (6 << 8))
#define MAP_LOST_WOODS1_ROOM4           (12 | (6 << 8))
#define MAP_LOST_WOODS1_ROOM5           (13 | (6 << 8))
#define MAP_LOST_WOODS1_ROOM6           (14 | (6 << 8))
#define MAP_LOST_WOODS1_ROOM7           (15 | (6 << 8))
#define MAP_LOST_WOODS1_ROOM8           (16 | (6 << 8))
#define MAP_LOST_WOODS1_ROOM9           (17 | (6 << 8))
#define MAP_LOST_WOODS1_ROOM10          (18 | (6 << 8))
#define MAP_LOST_WOODS1_UNDERWATER      (19 | (6 << 8))

// Map Group 7
#define MAP_PUZZLE_DESERT_OASIS (0 | (7 << 8))
#define MAP_DESERT_EAST         (1 | (7 << 8))
#define MAP_DESERT_NORTH        (2 | (7 << 8))
#define MAP_DESERT_WEST         (3 | (7 << 8))
#define MAP_DESERT_SOUTH        (4 | (7 << 8))

// Map Group 8
#define MAP_TRICK_TREAT_PETALBURG_CITY  (0 | (8 << 8))
#define MAP_TRICK_TREAT_MOSSDEEP_CITY   (1 | (8 << 8))
#define MAP_TRICK_TREAT_FORTREE_CITY    (2 | (8 << 8))
#define MAP_TRICK_TREAT_SLATEPORT_CITY1 (3 | (8 << 8))
#define MAP_TRICK_TREAT_SLATEPORT_CITY2 (4 | (8 << 8))

// Map Group 9
#define MAP_PUZZLE_SPOT_DIFFERENCE_HALLWAY (0 | (9 << 8))
#define MAP_PUZZLE_SPOT_DIFFERENCE_1_LEFT  (1 | (9 << 8))
#define MAP_PUZZLE_SPOT_DIFFERENCE_1_RIGHT (2 | (9 << 8))
#define MAP_PUZZLE_SPOT_DIFFERENCE_2_LEFT  (3 | (9 << 8))
#define MAP_PUZZLE_SPOT_DIFFERENCE_2_RIGHT (4 | (9 << 8))
#define MAP_PUZZLE_SPOT_DIFFERENCE_3_LEFT  (5 | (9 << 8))
#define MAP_PUZZLE_SPOT_DIFFERENCE_3_RIGHT (6 | (9 << 8))

// Map Group 10
#define MAP_PUZZLE_TRICK_HOUSE_CUT       (0 | (10 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_ORIGINAL2 (1 | (10 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_ORIGINAL3 (2 | (10 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_ORIGINAL4 (3 | (10 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_ORIGINAL5 (4 | (10 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_ORIGINAL6 (5 | (10 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_ORIGINAL7 (6 | (10 << 8))
#define MAP_PUZZLE_TRICK_HOUSE_ORIGINAL8 (7 | (10 << 8))
#define MAP_PUZZLE_TIN_TOWER_CLIMB       (8 | (10 << 8))
#define MAP_PUZZLE_WATER_TEMPLE          (9 | (10 << 8))
#define MAP_PUZZLE_MUSIC_NOTE_TILES      (10 | (10 << 8))
#define MAP_PUZZLE_LEDGE_MOUNTAIN        (11 | (10 << 8))
#define MAP_PUZZLE_WILKE                 (12 | (10 << 8))
#define MAP_PUZZLE_ROUTE110              (13 | (10 << 8))
#define MAP_PUZZLE_LOSS_FLOOR1           (14 | (10 << 8))
#define MAP_PUZZLE_LOSS_FLOOR2           (15 | (10 << 8))
#define MAP_PUZZLE_TWIN_MEMORIES         (16 | (10 << 8))
#define MAP_PUZZLE_HIDDEN_MAZE           (17 | (10 << 8))

#define MAP_GROUPS_COUNT 11

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
