#ifndef GUARD_CONSTANTS_MAP_SCRIPTS_H
#define GUARD_CONSTANTS_MAP_SCRIPTS_H

#define MAP_SCRIPT_ON_LOAD                      0x01
#define MAP_SCRIPT_ON_FRAME_TABLE               0x02
#define MAP_SCRIPT_ON_TRANSITION                0x03
#define MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE       0x04
#define MAP_SCRIPT_ON_RESUME                    0x05
#define MAP_SCRIPT_ON_DIVE_WARP                 0x06
#define MAP_SCRIPT_ON_RETURN_TO_FIELD           0x07
#define MAP_SCRIPT_ON_SPAWN_EVENT_OBJECT        0x08

#define MAP_SCRIPT_PUZZLE_HEADER_NAME           0x20
#define MAP_SCRIPT_PUZZLE_HEADER_AUTHOR         0x21
#define MAP_SCRIPT_PUZZLE_HEADER_PREREQ_LIST    0x22
#define MAP_SCRIPT_PUZZLE_HEADER_POST_LIST      0x23
#define MAP_SCRIPT_PUZZLE_HEADER_ADJECTIVE      0x24
#define MAP_SCRIPT_PUZZLE_HEADER_QUIP           0x25
#define MAP_SCRIPT_PUZZLE_META_VARIABLES        0x26
#define MAP_SCRIPT_PUZZLE_CANDY_LIST            0x27
#define MAP_SCRIPT_PUZZLE_CUSTOM_INTRO          0x28
#define MAP_SCRIPT_PUZZLE_DEV_COMMENTARY        0x29
#define MAP_SCRIPT_PUZZLE_FRIEND_COMMENTARY     0x2A

#define MAP_SCRIPT_PUZZLE_CUSTOM_INTRO_SCRIPT   0x40
#define MAP_SCRIPT_PUZZLE_SETUP_SCRIPT          0x41
#define MAP_SCRIPT_PUZZLE_TEARDOWN_SCRIPT       0x42
#define MAP_SCRIPT_PUZZLE_EXIT_SCRIPT           0x43
#define MAP_SCRIPT_PUZZLE_BLACKOUT_SCRIPT       0x44
#define MAP_SCRIPT_PUZZLE_ESCAPE_SCRIPT         0x45


#endif // GUARD_CONSTANTS_MAP_SCRIPTS_H
