SlateportCity_MapScripts:: @ 81DCC61
	.byte 0

SlateportCity_EventScript_1DCF36:: @ 81DCF36
	msgbox SlateportCity_Text_1DE8BC, MSGBOX_SIGN
	end
SlateportCity_Text_1DE8BC: @ 81DE8BC
	.string "BATTLE TENT SLATEPORT SITE\n"
	.string "“Find it! The ultimate POKéMON!”$"

SlateportCity_EventScript_1DCF3F:: @ 81DCF3F
	msgbox SlateportCity_Text_1DE9AA, MSGBOX_SIGN
	end
SlateportCity_Text_1DE9AA: @ 81DE9AA
	.string "STERN'S SHIPYARD\p"
	.string "“Boarding of the SLATEPORT-LILYCOVE\n"
	.string "ferry S.S. TIDAL is handled at the\l"
	.string "HARBOR.”$"

SlateportCity_EventScript_1DCF70:: @ 81DCF70
	msgbox SlateportCity_Text_1DEA0B, MSGBOX_SIGN
	end
SlateportCity_Text_1DEA0B: @ 81DEA0B
	.string "POKéMON FAN CLUB\n"
	.string "“Calling all fans of POKéMON!”$"

SlateportCity_EventScript_1DCF79:: @ 81DCF79
	msgbox SlateportCity_Text_1DEA3B, MSGBOX_SIGN
	end
SlateportCity_Text_1DEA3B: @ 81DEA3B
	.string "“The endless sea sustains\n"
	.string "all life.”\p"
	.string "OCEANIC MUSEUM$"

SlateportCity_EventScript_1DCF82:: @ 81DCF82
	msgbox SlateportCity_Text_1DEA6F, MSGBOX_SIGN
	end
SlateportCity_Text_1DEA6F: @ 81DEA6F
	.string "SLATEPORT CITY\p"
	.string "“The port where people and POKéMON\n"
	.string "cross paths.”$"

SlateportCity_EventScript_1DCF8B:: @ 81DCF8B
	msgbox SlateportCity_Text_1DEAAF, MSGBOX_SIGN
	end
SlateportCity_Text_1DEAAF: @ 81DEAAF
	.string "SLATEPORT MARKET\n"
	.string "“Unique items found nowhere else!”$"

SlateportCity_Text_1DEAE3: @ 81DEAE3
	.string "SLATEPORT HARBOR\p"
	.string "“The ferry S.S. TIDAL is under\n"
	.string "construction in the SHIPYARD.\p"
	.string "“Service is scheduled to begin\n"
	.string "shortly.”$"

SlateportCity_EventScript_1DCF94:: @ 81DCF94
	msgbox SlateportCity_Text_1DEB5A, MSGBOX_SIGN
	end
SlateportCity_Text_1DEB5A: @ 81DEB5A
	.string "SLATEPORT HARBOR\p"
	.string "“Enjoy a delightful cruise on\n"
	.string "the ferry S.S. TIDAL.”$"

SlateportCity_EventScript_1DCFB2:: @ 81DCFB2
	msgbox SlateportCity_Text_1DEBA0, MSGBOX_SIGN
	end
SlateportCity_Text_1DEBA0: @ 81DEBA0
	.string "NAME RATER'S HOUSE\n"
	.string "“POKéMON nicknames rated.”$"
