gText_Birch_Welcome:: @ 82C897B
	.string "Boo! Hahahaha!\p"
	.string "Happy Halloween! And welcome to\n"
	.string "the world of POKéMON!\p"
	.string "My name is BIRCH. But everyone\n"
	.string "calls me the POKéMON PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "But you knew that already, didn't you?\p"
	.string "You've been around this block\n"
	.string "once or twice, I can tell.\p"
	.string "You're probably still freaking out\n"
	.string "about my mask! Hahaha!\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "But let's move on!$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Which costume did you pick for\n"
	.string "Halloween this evening?$"

gText_Birch_ControlBoy::
	.string "Mudkid {DPAD_LEFT}$"
gText_Birch_ControlGirl::
	.string "{DPAD_RIGHT} Torchick$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "And what do you call yourself\n"
	.string "while in that getup?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Ah, okay! That's a swell costume you've\n"
	.string "got there {PLAYER}! The perfect thing\l"
	.string "to go TRICK-OR-TREATING in!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "I think I hear my kid {RIVAL} calling\n"
	.string "for you, {PLAYER}.\p"
	.string "Remember to have fun and grab as much\n"
	.string "candy as you can carry in your bag!\p"
	.string "I'll see you kids tonight when\n"
	.string "you get back!\p"
	.string "$"
