LilycoveCity_MapScripts:: @ 81E2B3C
	.byte 0

LilycoveCity_EventScript_1E2CFF:: @ 81E2CFF
	msgbox LilycoveCity_Text_1E448B, MSGBOX_SIGN
	end
LilycoveCity_Text_1E448B: @ 81E448B
	.string "LILYCOVE CITY\p"
	.string "“Where the land ends and the\n"
	.string "sea begins.”$"


LilycoveCity_EventScript_1E2D08:: @ 81E2D08
	msgbox LilycoveCity_Text_1E44C3, MSGBOX_SIGN
	end
LilycoveCity_Text_1E44C3: @ 81E44C3
	.string "POKéMON CONTEST HALL\n"
	.string "“The gathering place for TRAINERS!”$"


LilycoveCity_EventScript_1E2D11:: @ 81E2D11
	msgbox LilycoveCity_Text_1E44FC, MSGBOX_SIGN
	end
LilycoveCity_Text_1E44FC: @ 81E44FC
	.string "COVE LILY MOTEL\p"
	.string "“Remember us as COVE LILY of\n"
	.string "LILYCOVE.”$"


LilycoveCity_EventScript_1E2D1A:: @ 81E2D1A
	msgbox LilycoveCity_Text_1E4534, MSGBOX_SIGN
	end
LilycoveCity_Text_1E4534: @ 81E4534
	.string "LILYCOVE MUSEUM\p"
	.string "“POKéMON Masterpiece Collection\n"
	.string "on exhibit!”$"


LilycoveCity_EventScript_1E2D44:: @ 81E2D44
	msgbox LilycoveCity_Text_1E4624, MSGBOX_SIGN
	end
LilycoveCity_Text_1E4624: @ 81E4624
	.string "LILYCOVE CITY HARBOR\p"
	.string "“Enjoy a delightful cruise on\n"
	.string "the ferry S.S. TIDAL.”$"


LilycoveCity_EventScript_1E2D62:: @ 81E2D62
	msgbox LilycoveCity_Text_1E466E, MSGBOX_SIGN
	end
LilycoveCity_Text_1E466E: @ 81E466E
	.string "POKéMON TRAINER FAN CLUB\p"
	.string "The names of TRAINERS are scribbled\n"
	.string "all over the sign…$"


LilycoveCity_EventScript_1E2D6B:: @ 81E2D6B
	msgbox LilycoveCity_Text_1E46BE, MSGBOX_SIGN
	end
LilycoveCity_Text_1E46BE: @ 81E46BE
	.string "LILYCOVE DEPARTMENT STORE\p"
	.string "“Overflowing with great merchandise\n"
	.string "and excitement!\p"
	.string "“A great place to find that something\n"
	.string "you need!”$"


LilycoveCity_EventScript_1E2D74:: @ 81E2D74
	msgbox LilycoveCity_Text_1E473D, MSGBOX_SIGN
	end
LilycoveCity_Text_1E473D: @ 81E473D
	.string "MOVE DELETER'S HOUSE\p"
	.string "“Unwanted POKéMON moves deleted.”$"
