MossdeepCity_MapScripts:: @ 81E4A96
	.byte 0

MossdeepCity_EventScript_1E4B1D:: @ 81E4B1D
	msgbox MossdeepCity_Text_1E53A9, MSGBOX_SIGN
	end
MossdeepCity_Text_1E53A9: @ 81E53A9
	.string "MOSSDEEP CITY POKéMON GYM\n"
	.string "LEADERS: LIZA & TATE\p"
	.string "“The mystic combination!”$"

MossdeepCity_EventScript_1E4B26:: @ 81E4B26
	msgbox MossdeepCity_Text_1E53F2, MSGBOX_SIGN
	end
MossdeepCity_Text_1E53F2: @ 81E53F2
	.string "MOSSDEEP CITY\n"
	.string "“Our slogan: Cherish POKéMON!”$"

MossdeepCity_EventScript_1E4B2F:: @ 81E4B2F
	msgbox MossdeepCity_Text_1E541F, MSGBOX_SIGN
	end
MossdeepCity_Text_1E541F: @ 81E541F
	.string "MOSSDEEP SPACE CENTER\n"
	.string "“The closest place to space.”$"
