
Common_EventScript_ItemChocolateBar::
Common_EventScript_ItemPotion::
	giveitem_std ITEM_POTION, 1, 1
	end

Common_EventScript_ItemStarburst::
Common_EventScript_ItemAntidote::
	giveitem_std ITEM_ANTIDOTE, 1, 1
	end

Common_EventScript_ItemLemonDrop::
Common_EventScript_ItemBurnHeal::
	giveitem_std ITEM_BURN_HEAL, 1, 1
	end

Common_EventScript_ItemWarheads::
Common_EventScript_ItemIceHeal::
	giveitem_std ITEM_ICE_HEAL, 1, 1
	end

Common_EventScript_ItemPretzels::
Common_EventScript_ItemAwakening::
	giveitem_std ITEM_AWAKENING, 1, 1
	end

Common_EventScript_ItemVeroMango::
Common_EventScript_ItemParlyzHeal::
	giveitem_std ITEM_PARALYZE_HEAL, 1, 1
	end

Common_EventScript_Item100GrandBar::
Common_EventScript_ItemHundredGrandBar::
Common_EventScript_ItemGrandBar::
Common_EventScript_ItemFullRestore::
	giveitem_std ITEM_FULL_RESTORE, 1, 1
	end

Common_EventScript_ItemWhiteChoco::
Common_EventScript_ItemMaxPotion::
	giveitem_std ITEM_MAX_POTION, 1, 1
	end

Common_EventScript_ItemButterfinger::
Common_EventScript_ItemHyperPotion::
	giveitem_std ITEM_HYPER_POTION, 1, 1
	end

Common_EventScript_ItemTwix::
Common_EventScript_ItemSuperPotion::
	giveitem_std ITEM_SUPER_POTION, 1, 1
	end

Common_EventScript_ItemReeseCups::
Common_EventScript_ItemFullHeal::
	giveitem_std ITEM_FULL_HEAL, 1, 1
	end

Common_EventScript_ItemRevive::
	giveitem_std ITEM_REVIVE, 1, 1
	end

Common_EventScript_ItemFreshWater::
	giveitem_std ITEM_FRESH_WATER, 1, 1
	end

Common_EventScript_ItemSodaPop::
	giveitem_std ITEM_SODA_POP, 1, 1
	end

Common_EventScript_ItemLemonade::
	giveitem_std ITEM_LEMONADE, 1, 1
	end

Common_EventScript_ItemMoomooMilk::
	giveitem_std ITEM_MOOMOO_MILK, 1, 1
	end

Common_EventScript_ItemCarrotStick::
Common_EventScript_ItemEnergyPowder::
	giveitem_std ITEM_ENERGY_POWDER, 1, 1
	end

Common_EventScript_ItemAppleSlice::
Common_EventScript_ItemEnergyRoot::
	giveitem_std ITEM_ENERGY_ROOT, 1, 1
	end

Common_EventScript_ItemPrune::
Common_EventScript_ItemHealPowder::
	giveitem_std ITEM_HEAL_POWDER, 1, 1
	end

Common_EventScript_ItemCeleryStick::
Common_EventScript_ItemRivialHerb::
	giveitem_std ITEM_REVIVAL_HERB, 1, 1
	end

Common_EventScript_ItemMaltesers::
Common_EventScript_ItemEther::
	giveitem_std ITEM_ETHER, 1, 1
	end

Common_EventScript_ItemCadburyCreme::
Common_EventScript_ItemMaxEther::
	giveitem_std ITEM_MAX_ETHER, 1, 1
	end

Common_EventScript_ItemSnowball::
Common_EventScript_ItemElixer::
	giveitem_std ITEM_ELIXIR, 1, 1
	end

Common_EventScript_ItemTurkishDelight::
Common_EventScript_ItemMaxElixer::
	giveitem_std ITEM_MAX_ELIXIR, 1, 1
	end

Common_EventScript_ItemOreoCookie::
Common_EventScript_ItemLavaCookie::
	giveitem_std ITEM_LAVA_COOKIE, 1, 1
	end

Common_EventScript_ItemMMMinis::
Common_EventScript_ItemTinyMushroom::
	giveitem_std ITEM_TINY_MUSHROOM, 1, 1
	end

Common_EventScript_ItemMMBig::
Common_EventScript_ItemBigMushroom::
	giveitem_std ITEM_BIG_MUSHROOM, 1, 1
	end

Common_EventScript_ItemGobstopper::
Common_EventScript_ItemPearl::
	giveitem_std ITEM_PEARL, 1, 1
	end

Common_EventScript_ItemGiantChocoSlab::
Common_EventScript_ItemBigPearl::
	giveitem_std ITEM_BIG_PEARL, 1, 1
	end

Common_EventScript_ItemPixieStix::
Common_EventScript_ItemStardust::
	giveitem_std ITEM_STARDUST, 1, 1
	end

Common_EventScript_ItemFerreroRocher::
Common_EventScript_ItemStarPiece::
	giveitem_std ITEM_STAR_PIECE, 1, 1
	end

Common_EventScript_ItemToblerone::
Common_EventScript_ItemNugget::
	giveitem_std ITEM_NUGGET, 1, 1
	end

Common_EventScript_ItemGummyBear::
Common_EventScript_ItemHeartScale::
	giveitem_std ITEM_HEART_SCALE, 1, 1
	end

Common_EventScript_ItemRareCandy::
	giveitem_std ITEM_RARE_CANDY, 1, 1
	end

Common_EventScript_ItemPokeDoll::
	giveitem_std ITEM_POKE_DOLL, 1, 1
	end

Common_EventScript_ItemFluffyTail::
	giveitem_std ITEM_FLUFFY_TAIL, 1, 1
	end

Common_EventScript_ItemItemfinder::
	giveitem_std ITEM_ITEMFINDER, 1, 1
	end

@ -----------------------------------------------------

Common_EventScript_PickupRareItem::
	giveitem_std ITEM_RARE_CANDY, 1, 1
	end

