
.align 2
Puzzle_SafariImposters_TalkTables::
	@ Joey
	.4byte Puzzle_SafariImposters_TalkTable_JoeyAlibi
	.4byte Puzzle_SafariImposters_TalkTable_JoeyImposter
	.4byte Puzzle_SafariImposters_TalkTable_JoeyAccuse
	@ James
	.4byte Puzzle_SafariImposters_TalkTable_JoeyAlibi
	.4byte Puzzle_SafariImposters_TalkTable_JoeyImposter
	.4byte Puzzle_SafariImposters_TalkTable_JoeyAccuse
	@ Irene
	.4byte Puzzle_SafariImposters_TalkTable_JoeyAlibi
	.4byte Puzzle_SafariImposters_TalkTable_JoeyImposter
	.4byte Puzzle_SafariImposters_TalkTable_JoeyAccuse
	@ Wally
	.4byte Puzzle_SafariImposters_TalkTable_JoeyAlibi
	.4byte Puzzle_SafariImposters_TalkTable_JoeyImposter
	.4byte Puzzle_SafariImposters_TalkTable_JoeyAccuse
	@ Brendan
	.4byte Puzzle_SafariImposters_TalkTable_JoeyAlibi
	.4byte Puzzle_SafariImposters_TalkTable_JoeyImposter
	.4byte Puzzle_SafariImposters_TalkTable_JoeyAccuse
	@ May
	.4byte Puzzle_SafariImposters_TalkTable_JoeyAlibi
	.4byte Puzzle_SafariImposters_TalkTable_JoeyImposter
	.4byte Puzzle_SafariImposters_TalkTable_JoeyAccuse
	@ Alex
	.4byte Puzzle_SafariImposters_TalkTable_JoeyAlibi
	.4byte Puzzle_SafariImposters_TalkTable_JoeyImposter
	.4byte Puzzle_SafariImposters_TalkTable_JoeyAccuse

@ -----------------------------------------------------
@ Joey

.align 2
Puzzle_SafariImposters_TalkTable_JoeyAlibi:
	.4byte 0
Puzzle_SafariImposters_TalkTable_JoeyImposter:
	.4byte 0
Puzzle_SafariImposters_TalkTable_JoeyAccuse:
	.4byte 0


Puzzle_SafariImposters_Talk_Joey_Alibi1:
	.string ""


