RustboroCity_MapScripts:: @ 81E06BD
	.byte 0

RustboroCity_EventScript_1E08DA:: @ 81E08DA
	msgbox RustboroCity_Text_1E1695, MSGBOX_SIGN
	end
RustboroCity_Text_1E1695: @ 81E1695
	.string "POKéMON TRAINER'S SCHOOL!\p"
	.string "If I go to this school, will I be able\n"
	.string "to catch rare POKéMON easily?$"


RustboroCity_EventScript_1E08E3:: @ 81E08E3
	msgbox RustboroCity_Text_1E20A6, MSGBOX_SIGN
	end
RustboroCity_Text_1E20A6: @ 81E20A6
	.string "“Timesaving tunnel nearing\n"
	.string "completion!”$"


RustboroCity_EventScript_1E08EC:: @ 81E08EC
	msgbox RustboroCity_Text_1E2128, MSGBOX_SIGN
	end
RustboroCity_Text_1E2128: @ 81E2128
	.string "DEVON CORPORATION\p"
	.string "“For all your living needs, we make\n"
	.string "it all.”$"


RustboroCity_EventScript_1E08F5:: @ 81E08F5
	msgbox RustboroCity_Text_1E2167, MSGBOX_SIGN
	end
RustboroCity_Text_1E2167: @ 81E2167
	.string "RUSTBORO CITY POKéMON GYM\n"
	.string "LEADER: ROXANNE\p"
	.string "“The ROCK-loving honors student!”$"


RustboroCity_EventScript_1E08FE:: @ 81E08FE
	msgbox RustboroCity_Text_1E21B3, MSGBOX_SIGN
	end
RustboroCity_Text_1E21B3: @ 81E21B3
	.string "DEVON CORP. BRANCH OFFICE\p"
	.string "“Access limited to DEVON employees\n"
	.string "and authorized personnel.”$"


RustboroCity_EventScript_1E0907:: @ 81E0907
	msgbox RustboroCity_Text_1E220B, MSGBOX_SIGN
	end
RustboroCity_Text_1E220B: @ 81E220B
	.string "RUSTBORO CITY\p"
	.string "“The city probing the integration of\n"
	.string "nature and science.”$"


RustboroCity_EventScript_1E0910:: @ 81E0910
	msgbox RustboroCity_Text_1E2253, MSGBOX_SIGN
	end
RustboroCity_Text_1E2253: @ 81E2253
	.string "POKéMON TRAINER'S SCHOOL\p"
	.string "“We'll teach you anything about\n"
	.string "POKéMON!”$"


RustboroCity_EventScript_1E0919:: @ 81E0919
	msgbox RustboroCity_Text_1E2296, MSGBOX_SIGN
	end
RustboroCity_Text_1E2296: @ 81E2296
	.string "CUTTER'S HOUSE$"

