.align 2												@ Estimated Challenge Ratings out of 10
gPuzzleList::											@ TPP / Single Player
	.2byte MAP_EMPTY_PUZZLE								@ [Debug]
	.2byte MAP_PUZZLE_TRICK_HOUSE_CUT					@  2 / 2
	.2byte MAP_PUZZLE_TRICK_HOUSE_TRAPDOORS				@  2 / 2
	.2byte MAP_PUZZLE_WATER_TEMPLE						@  5 / 4
	.2byte MAP_PUZZLE_TIN_TOWER_CLIMB					@  6 / 4
	.2byte MAP_PUZZLE_MUSIC_NOTE_TILES					@  6 / 3
	.2byte MAP_PUZZLE_LEDGE_MOUNTAIN					@  8 / 4
	.2byte MAP_PUZZLE_WILKE								@ 10 / 8
	.2byte 0xFFFF
