PetalburgCity_MapScripts::
	.byte 0

PetalburgCity_EventScript_1DC476:: @ 81DC476
	msgbox PetalburgCity_Text_1DCAAA, MSGBOX_SIGN
	end
PetalburgCity_Text_1DCAAA: @ 81DCAAA
	.string "PETALBURG CITY POKéMON GYM\n"
	.string "LEADER: NORMAN\l"
	.string "“A man in pursuit of power!”$"

PetalburgCity_EventScript_1DC47F:: @ 81DC47F
	msgbox PetalburgCity_Text_1DCAF1, MSGBOX_SIGN
	end
PetalburgCity_Text_1DCAF1: @ 81DCAF1
	.string "PETALBURG CITY\n"
	.string "“Where people mingle with nature.”$"

PetalburgCity_EventScript_1DC491:: @ 81DC491
	msgbox PetalburgCity_Text_1DCB23, MSGBOX_SIGN
	end
PetalburgCity_Text_1DCB23: @ 81DCB23
	.string "WALLY'S HOUSE$"
