LavaridgeTown_MapScripts:: @ 81EA4D3
	.byte 0

LavaridgeTown_EventScript_1EA7A5:: @ 81EA7A5
	msgbox LavaridgeTown_Text_1EB12B, MSGBOX_SIGN
	end
LavaridgeTown_Text_1EB12B: @ 81EB12B
	.string "LAVARIDGE TOWN\p"
	.string "“POKéMON CENTER HOT SPRINGS\n"
	.string "An excellent place for relaxing!”$"

LavaridgeTown_EventScript_1EA7AE:: @ 81EA7AE
	msgbox LavaridgeTown_Text_1EB178, MSGBOX_SIGN
	end
LavaridgeTown_Text_1EB178: @ 81EB178
	.string "LAVARIDGE TOWN POKéMON GYM\n"
	.string "LEADER: FLANNERY\l"
	.string "“One with a fiery passion that burns!”$"

LavaridgeTown_EventScript_1EA7B7:: @ 81EA7B7
	msgbox LavaridgeTown_Text_1EB1CB, MSGBOX_SIGN
	end
LavaridgeTown_Text_1EB1CB: @ 81EB1CB
	.string "POKéMON HERB SHOP\n"
	.string "“Bitter taste--better cure!”$"
